### ISSUE TITLE
generateTests method in class TwigGenerator behavior is strange 

### ISSUE THREAD

**Issue by peter279k** [adhocore/phint#50]
## Introduction

**This is a**

- [x] Bug/Issue
## Describe the bug/issue

Consider the following code snippets:

```php
...
        if (!$this->twig) {
            $this->initTwig();
        }

        $count = 0;

        foreach ($testMetadata as $metadata) {
            // Skip existing
            if (\is_file($targetFile = $metadata['testPath'])) {
                continue;
            }

            $content = $this->twig->render('tests/test.twig', $metadata + $parameters);
            $count += (int) $this->pathUtil->writeFile($targetFile, $content);
        }

        return $count;
...
```

### What happened

If the `$targetFile` is file then do the next work in for loop.

And the `$this->pathUtil->writeFile` will pass the `directory` pah when the `$targetFile` is the directory.

### What is expected

I think the `$targetFile` should be the file, not directory and I think the condition should be change into:

```php
...
if (\is_dir($targetFile = $metadata['testPath'])) {
        continue;
}
...
```

**Comment by adhocore** [comment]
thank you for time taking and filing issue.
that check is for not overwriting existing test file (the `$metadata['testPath']` is actually full file path and not dir)

**Comment by peter279k** [comment]
Ok. It ,makes sense. I will close issue.
